# 端口号
server:
  port:
    8081
# MySQL相关配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fatty_corps?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
# MybatisPlus相关配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印